FROM node:20

# Install pnpm
RUN corepack enable && corepack prepare pnpm@8.6.1 --activate

WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of the application
COPY . .

# Expose the port
EXPOSE 3000

# Start the development server, attention: this is for development, not for production
CMD ["pnpm", "dev"]
